// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: minio.proto

package minio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Minio_GetPresignedUrl_FullMethodName = "/minio.Minio/GetPresignedUrl"
)

// MinioClient is the client API for Minio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinioClient interface {
	GetPresignedUrl(ctx context.Context, in *GetPresignedUrlRequest, opts ...grpc.CallOption) (*GetPresignedUrlResponse, error)
}

type minioClient struct {
	cc grpc.ClientConnInterface
}

func NewMinioClient(cc grpc.ClientConnInterface) MinioClient {
	return &minioClient{cc}
}

func (c *minioClient) GetPresignedUrl(ctx context.Context, in *GetPresignedUrlRequest, opts ...grpc.CallOption) (*GetPresignedUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresignedUrlResponse)
	err := c.cc.Invoke(ctx, Minio_GetPresignedUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinioServer is the server API for Minio service.
// All implementations must embed UnimplementedMinioServer
// for forward compatibility.
type MinioServer interface {
	GetPresignedUrl(context.Context, *GetPresignedUrlRequest) (*GetPresignedUrlResponse, error)
	mustEmbedUnimplementedMinioServer()
}

// UnimplementedMinioServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinioServer struct{}

func (UnimplementedMinioServer) GetPresignedUrl(context.Context, *GetPresignedUrlRequest) (*GetPresignedUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresignedUrl not implemented")
}
func (UnimplementedMinioServer) mustEmbedUnimplementedMinioServer() {}
func (UnimplementedMinioServer) testEmbeddedByValue()               {}

// UnsafeMinioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinioServer will
// result in compilation errors.
type UnsafeMinioServer interface {
	mustEmbedUnimplementedMinioServer()
}

func RegisterMinioServer(s grpc.ServiceRegistrar, srv MinioServer) {
	// If the following call pancis, it indicates UnimplementedMinioServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Minio_ServiceDesc, srv)
}

func _Minio_GetPresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinioServer).GetPresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Minio_GetPresignedUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinioServer).GetPresignedUrl(ctx, req.(*GetPresignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Minio_ServiceDesc is the grpc.ServiceDesc for Minio service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Minio_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minio.Minio",
	HandlerType: (*MinioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPresignedUrl",
			Handler:    _Minio_GetPresignedUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minio.proto",
}
